# Generated by Django 3.0 on 2020-01-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
