# Generated by Django 3.0 on 2020-01-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_0055'),
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asker',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
