# Generated by Django 3.0 on 2020-01-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_1559'),
        ('ask', '0004_auto_20200127_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('question', models.ManyToManyField(to='ask.Question')),
            ],
        ),
    ]
