# Generated by Django 3.0 on 2020-01-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_1559'),
        ('ask', '0005_profilequestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileQuestion',
            new_name='ProfileInfo',
        ),
    ]
