# Generated by Django 3.0 on 2020-01-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_auto_20200129_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
