# Generated by Django 3.0 on 2020-01-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_1559'),
        ('ask', '0007_delete_profileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asker', to='users.Profile'),
        ),
    ]
